const express = require("express");
const router = express.Router();
const { TherapistRegister, Login , TherapistLogout , getAllnames} = require("../Controllers/Therapist-Controller");
const { PatientRegister , PatientLogin , PatientLogout , getAllpatient} = require("../Controllers/Patient-Controller");
const { AdminRegister , AdminLogin , countTherapist , countPatient} = require("../Controllers/Admin-controller");
const { uploadBooks , addBooks , uploadVedios , addVedios} = require("../Controllers/Resource-Controller");
router.post("/therapist/register",TherapistRegister);
router.post("/therapist/login",Login);
router.post("/therapist/logout",TherapistLogout);
router.post("/patient/register",PatientRegister );
router.post("/patient/login",PatientLogin);
router.post("/patient/logout",PatientLogout);
router.get("/therapist/getallnames",getAllnames);
router.get("/patient/getallpatient",getAllpatient);
router.post("/admin/register",AdminRegister);
router.post("/admin/login",AdminLogin);
router.get("/admin/count-therapist",countTherapist);
router.get("/admin/count-patient",countPatient);
router.post("/admin/upload-book",uploadBooks.single("file"),addBooks);
router.post("/admin/upload-vedio",uploadVedios.single("file"),addVedios);
module.exports = router;
